name: first workflow

on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: print hello
        run: echo "hello"
        
      - name: checkout repo
        uses: actions/checkout@v4.3.0

      - name: list the repo files
        run: ls -la

      
