on:
  repository_dispatch:
    types: [incident_report]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        run: echo "deploy app to ${{ inputs.environment }}"
