name: push-pr

on:
    push:
        branches:
            - main
            - "release/**"
        paths:
            - "src/**"
    pull_request:
        branches:
            - main
            - "release/**"
        paths:
            - "src/**"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.3.0
            
            - name: Run test
              run: npm test